---
title: "ReadingDataAssignment"
author: "Josh Marciniak"
date: "February 15, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###10.1 E1
#Writing a code chunk that reads two remote datasets, train.csv and test.csv
```{r}
library(tidyverse)
train <- read_csv("https://www.iun.edu/~cisjw/ds/files/data/train.csv",
  col_types = cols(
  Survived = col_character(),
  Pclass = col_character(),
  Name = col_character(),
  Sex = col_character(),
  Age = col_integer(),
  SibSp = col_integer(),
  ParentChild = col_integer(),
  TicketNumber = col_character(),
  Fare = col_double(),
  Cabin = col_character(),
  Port = col_character(),
  LiftBoat = col_integer()
), na="NA")
test <- read_csv("https://www.iun.edu/~cisjw/ds/files/data/test.csv",
  col_types = cols(
  Survived = col_character(),
  Pclass = col_character(),
  Name = col_character(),
  Sex = col_character(),
  Age = col_integer(),
  SibSp = col_integer(),
  ParentChild = col_integer(),
  TicketNumber = col_character(),
  Fare = col_double(),
  Cabin = col_character(),
  Port = col_character(),
  LiftBoat = col_integer()
),na="NA")
train
test
```
###10.3 E3
```{r}
train%>%
  as_tibble%>%
  filter(!is.na(Age))%>%
  summarise(avg.age=mean(Age))
```
###10.4 E4
#Selecting only the female passengers from train
```{r}
train%>%
  as_tibble%>%
  filter(Sex=="Female")
```
###10.5 E5
#Selecting survived femal rows from train and finding the total of survived females
```{r}
train%>%
  as_tibble%>%
  filter(Sex=="Female", Survived == "Yes")
```

